"""
Type stubs for laziest-import

This file provides complete type hints for IDE support including
IntelliSense, auto-completion, and type checking.

Usage:
    No action needed - Python automatically uses .pyi files alongside
    .py files when present in the same package directory.

IDE Support:
    - VS Code: Works automatically with Python extension
    - PyCharm: Works automatically
    - IDLE: Limited support; see IDLE_NOTES.md for details
"""

from typing import Dict, List, Optional, Set, Any, Tuple, Callable, Union
from types import ModuleType
from pathlib import Path

__version__: str

# ============== Initialization State ==============

def is_initializing() -> bool: ...
def is_initialized() -> bool: ...
def is_init_failed() -> bool: ...
def get_init_error() -> Optional[str]: ...
def reset_init_state() -> None: ...
def get_init_lock() -> object: ...  # threading.RLock

# ============== LazyModule Classes ==============

class LazyModule:
    """Lazy loading module proxy class."""
    def __getattr__(self, name: str) -> Any: ...
    def __dir__(self) -> List[str]: ...
    def __repr__(self) -> str: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

class LazySubmodule:
    """Lazy loading submodule proxy class."""
    def __getattr__(self, name: str) -> Any: ...
    def __dir__(self) -> List[str]: ...
    def __repr__(self) -> str: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

class LazySymbol:
    """Lazy loading symbol (class/function) proxy class."""
    def __getattr__(self, name: str) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...
    def __dir__(self) -> List[str]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __enter__(self) -> Any: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...
    def get_underlying_class(self) -> type: ...

class LazyProxy:
    """Intelligent module recognition proxy."""
    def __getattr__(self, name: str) -> Union[LazyModule, LazySymbol, Any]: ...
    def __dir__(self) -> List[str]: ...

lazy: LazyProxy

def _get_lazy_module(name: str) -> LazyModule: ...

# ============== Alias Management ==============

def register_alias(alias: str, module_name: str) -> None: ...
def register_aliases(aliases: Dict[str, str]) -> List[str]: ...
def unregister_alias(alias: str) -> bool: ...
def list_loaded() -> List[str]: ...
def list_available() -> List[str]: ...
def get_module(alias: str) -> Optional[ModuleType]: ...
def clear_cache() -> None: ...
def reload_aliases() -> None: ...
def reload_mappings() -> None: ...

def get_config_paths() -> List[str]: ...
def get_config_dirs() -> List[str]: ...

# ============== Version & Reload ==============

def get_version(alias: str) -> Optional[str]: ...
def reload_module(alias: str) -> bool: ...

# ============== Auto-search ==============

def enable_auto_search() -> None: ...
def disable_auto_search() -> None: ...
def is_auto_search_enabled() -> bool: ...
def search_module(name: str) -> Optional[str]: ...
def search_class(class_name: str) -> Optional[Tuple[str, Any]]: ...
def rebuild_module_cache() -> None: ...

# ============== Symbol Search ==============

class SearchResult:
    module_name: str
    symbol_name: str
    symbol_type: str  # 'class', 'function', 'callable'
    signature: Optional[str]
    score: float
    obj: Optional[Any]

class SymbolMatch:
    module_name: str
    symbol_name: str
    symbol_type: str
    signature: Optional[str]
    confidence: float
    source: str  # 'exact', 'user_pref', 'context', 'priority', 'fuzzy', 'misspelling'
    obj: Optional[Any]

def enable_symbol_search(
    interactive: bool = True,
    exact_params: bool = False,
    max_results: int = 5,
    search_depth: int = 1,
    skip_stdlib: bool = False,
) -> None: ...
def disable_symbol_search() -> None: ...
def is_symbol_search_enabled() -> bool: ...
def search_symbol(
    name: str,
    symbol_type: Optional[str] = None,
    signature: Optional[str] = None,
    max_results: Optional[int] = None,
) -> List[SearchResult]: ...
def rebuild_symbol_index() -> None: ...
def get_symbol_search_config() -> Dict[str, Any]: ...
def get_symbol_cache_info() -> Dict[str, Any]: ...
def clear_symbol_cache() -> None: ...

# ============== Symbol Resolution ==============

def set_symbol_preference(symbol: str, module: str) -> None: ...
def get_symbol_preference(symbol: str) -> Optional[str]: ...
def clear_symbol_preference(symbol: str) -> bool: ...
def list_symbol_conflicts(symbol: str) -> List[Dict[str, Any]]: ...
def set_module_priority(module: str, priority: int) -> None: ...
def get_module_priority(module: str) -> int: ...
def enable_auto_symbol_resolution(
    auto: bool = True,
    threshold: float = 0.7,
    warn_on_conflict: bool = True,
    context_aware: bool = True,
) -> None: ...
def disable_auto_symbol_resolution() -> None: ...
def get_symbol_resolution_config() -> Dict[str, Any]: ...
def get_loaded_modules_context() -> Set[str]: ...

# ============== Configuration ==============

def validate_aliases(aliases: Optional[Dict[str, str]] = None) -> Dict[str, List[str]]: ...
def validate_aliases_importable(
    aliases: Optional[Dict[str, str]] = None,
) -> Dict[str, Dict[str, Any]]: ...
def export_aliases(path: Optional[str] = None, include_categories: bool = True) -> str: ...

# ============== Debug & Statistics ==============

def enable_debug_mode() -> None: ...
def disable_debug_mode() -> None: ...
def is_debug_mode() -> bool: ...
def get_import_stats() -> Dict[str, Any]: ...
def reset_import_stats() -> None: ...

# ============== Import Hooks ==============

def add_pre_import_hook(hook: Callable[[str], None]) -> None: ...
def add_post_import_hook(hook: Callable[[str, Any], None]) -> None: ...
def remove_pre_import_hook(hook: Callable[[str], None]) -> bool: ...
def remove_post_import_hook(hook: Callable[[str, Any], None]) -> bool: ...
def clear_import_hooks() -> None: ...

# ============== Async Import ==============

async def import_async(alias: str) -> Any: ...
async def import_multiple_async(aliases: List[str]) -> Dict[str, Any]: ...

# ============== Retry Configuration ==============

def enable_retry(
    max_retries: int = 3, retry_delay: float = 0.5, modules: Optional[Set[str]] = None
) -> None: ...
def disable_retry() -> None: ...
def is_retry_enabled() -> bool: ...

# ============== File Cache ==============

class FileCache:
    file_path: str
    file_sha: str
    loaded_modules: List[str]
    timestamp: float
    def to_dict(self) -> Dict[str, Any]: ...

def enable_file_cache() -> None: ...
def disable_file_cache() -> None: ...
def is_file_cache_enabled() -> bool: ...
def clear_file_cache(file_path: Optional[str] = None) -> int: ...
def get_file_cache_info() -> Dict[str, Any]: ...
def force_save_cache() -> bool: ...

# ============== Cache Configuration ==============

def set_cache_config(
    symbol_index_ttl: Optional[int] = None,
    stdlib_cache_ttl: Optional[int] = None,
    third_party_cache_ttl: Optional[int] = None,
    enable_compression: Optional[bool] = None,
    max_cache_size_mb: Optional[int] = None,
) -> None: ...
def get_cache_config() -> Dict[str, Any]: ...
def get_cache_stats() -> Dict[str, Any]: ...
def reset_cache_stats() -> None: ...
def invalidate_package_cache(package_name: str) -> bool: ...
def enable_cache_compression(enabled: bool = True) -> None: ...

# ============== Cache Directory ==============

def set_cache_dir(path: Union[str, Path]) -> None: ...
def get_cache_dir() -> Path: ...
def reset_cache_dir() -> None: ...

# ============== Package Version ==============

def get_package_version(package_name: str) -> Optional[str]: ...
def get_all_package_versions() -> Dict[str, str]: ...
def get_laziest_import_version() -> str: ...
def get_cache_version() -> str: ...

# ============== Incremental Index ==============

def enable_incremental_index(enabled: bool = True) -> None: ...
def enable_background_build(enabled: bool = True) -> None: ...
def enable_cache_compression(enabled: bool = True) -> None: ...
def get_incremental_config() -> Dict[str, Any]: ...
def get_preheat_config() -> Dict[str, Any]: ...

# ============== Auto Install ==============

def enable_auto_install(
    interactive: bool = True,
    index: Optional[str] = None,
    extra_args: Optional[List[str]] = None,
    prefer_uv: bool = False,
    silent: bool = False,
) -> None: ...
def disable_auto_install() -> None: ...
def is_auto_install_enabled() -> bool: ...
def install_package(
    package_name: str,
    index: Optional[str] = None,
    extra_args: Optional[List[str]] = None,
    interactive: Optional[bool] = None,
) -> bool: ...
def get_auto_install_config() -> Dict[str, Any]: ...
def set_pip_index(url: Optional[str]) -> None: ...
def set_pip_extra_args(args: List[str]) -> None: ...

# ============== Easter Egg & Help ==============

def easter_egg(name: str = "default") -> str: ...
def help(topic: Optional[str] = None) -> str: ...

# ============== Module Introspection ==============

def list_module_symbols(
    module_name: str,
    include_private: bool = False,
    include_submodules: bool = True,
    filter_types: Optional[Set[str]] = None,
) -> List[str]: ...
def get_module_info(module_name: str) -> Dict[str, Any]: ...
def search_in_module(module_name: str, pattern: str) -> List[str]: ...

# ============== Symbol Location ==============

class SymbolLocation:
    module_name: str
    symbol_name: str
    symbol_type: str
    file_path: Optional[str]
    line_number: Optional[int]
    doc: Optional[str]
    signature: Optional[str]
    def __init__(
        self,
        module_name: str,
        symbol_name: str,
        symbol_type: str,
        file_path: Optional[str] = None,
        line_number: Optional[int] = None,
        doc: Optional[str] = None,
        signature: Optional[str] = None,
    ) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...

def which(
    symbol_name: str, module_hint: Optional[str] = None
) -> Optional[SymbolLocation]: ...
def which_all(symbol_name: str) -> List[SymbolLocation]: ...

# ============== Background Index ==============

def start_background_index_build(
    progress_callback: Optional[Callable[[str, float], None]] = None,
    timeout: Optional[float] = None,
) -> bool: ...
def is_index_building() -> bool: ...
def wait_for_index(timeout: Optional[float] = None) -> bool: ...

# ============== RC Config ==============

def load_rc_config() -> Dict[str, Any]: ...
def get_rc_value(key: str, default: Any = None) -> Any: ...
def create_rc_file(path: Optional[str] = None, template: bool = True) -> str: ...
def get_rc_info() -> Dict[str, Any]: ...
def reload_rc_config() -> None: ...
def save_rc_config(config: Dict[str, Any], path: Optional[str] = None) -> None: ...
def list_rc_paths() -> List[str]: ...

# ============== Reset All ==============

def reset_all() -> None: ...

# ============== Analysis & Profiling ==============

class PreAnalysisResult:
    file_path: str
    predicted_imports: Set[str]
    used_symbols: Set[str]
    confidence: Dict[str, float]

class ModuleProfile:
    module_name: str
    load_time: float
    memory_before: int
    memory_after: int
    memory_delta: int
    access_count: int
    first_access: Optional[float]
    last_access: Optional[float]

class ProfileReport:
    total_time: float
    total_memory: int
    modules: Dict[str, ModuleProfile]
    heavy_modules: List[str]
    slow_modules: List[str]
    recommendations: List[str]

class EnvironmentInfo:
    python_version: str
    executable: str
    virtual_env: Optional[str]
    venv_type: Optional[str]
    site_packages: List[str]
    installed_packages: Dict[str, str]

class DependencyNode:
    module_name: str
    is_available: bool
    is_stdlib: bool
    is_third_party: bool
    is_local: bool
    version: Optional[str]
    children: List["DependencyNode"]
    depth: int
    def to_dict(self) -> Dict[str, Any]: ...

class DependencyTree:
    root_module: str
    total_modules: int
    stdlib_count: int
    third_party_count: int
    local_count: int
    unavailable_count: int
    max_depth: int
    tree: Optional[DependencyNode]
    circular_dependencies: List[Tuple[str, str]]
    def to_dict(self) -> Dict[str, Any]: ...

class BenchmarkResult:
    name: str
    iterations: int
    total_time: float
    avg_time: float
    min_time: float
    max_time: float
    std_dev: float
    memory_before: int
    memory_after: int
    memory_delta: int

class BenchmarkReport:
    results: List[BenchmarkResult]
    comparison: Dict[str, float]
    recommendations: List[str]

class ImportComparison:
    module_name: str
    regular_import_time: float
    lazy_import_time: float
    speedup_factor: float
    regular_memory: int
    lazy_memory: int

class BenchmarkRunner:
    def __init__(
        self,
        warmup_iterations: int = 3,
        default_iterations: int = 10,
        use_gc: bool = True,
    ) -> None: ...
    def benchmark_function(
        self, name: str, func: Callable, iterations: Optional[int] = None
    ) -> BenchmarkResult: ...
    def benchmark_import(self, module_name: str, iterations: Optional[int] = None) -> BenchmarkResult: ...
    def benchmark_lazy_import(self, module_name: str, iterations: Optional[int] = None) -> BenchmarkResult: ...
    def compare_import_methods(self, module_name: str, iterations: Optional[int] = None) -> ImportComparison: ...
    def run_suite(self, benchmarks: List[Dict[str, Any]]) -> BenchmarkReport: ...

def analyze_file(file_path: str) -> PreAnalysisResult: ...
def analyze_source(source: str, file_path: str = "<string>") -> PreAnalysisResult: ...
def analyze_directory(
    dir_path: str,
    recursive: bool = True,
    exclude: Optional[Set[str]] = None,
) -> List[PreAnalysisResult]: ...

def start_profiling() -> None: ...
def stop_profiling() -> None: ...
def get_profile_report(top_n: int = 10) -> ProfileReport: ...
def print_profile_report(top_n: int = 10) -> None: ...

def find_symbol_conflicts() -> Dict[str, Any]: ...
def show_conflicts(
    symbol_filter: Optional[str] = None,
    max_results: int = 20,
) -> None: ...
def get_conflicts_summary() -> Dict[str, Any]: ...
def detect_environment() -> EnvironmentInfo: ...
def show_environment() -> None: ...

def benchmark(
    func: Optional[Callable] = None,
    *,
    name: Optional[str] = None,
    iterations: int = 10,
    warmup: int = 3,
) -> BenchmarkResult: ...
def benchmark_imports(
    modules: List[str],
    iterations: int = 5,
    compare_lazy: bool = True,
) -> BenchmarkReport: ...
def print_benchmark_report(report: BenchmarkReport) -> None: ...

# ============== Symbol Sharding ==============

def search_with_sharding(symbol_name: str, max_results: int = 5) -> List[SearchResult]: ...
def enable_sharding(enabled: bool = True) -> None: ...
def disable_sharding() -> None: ...
def get_sharding_config() -> Dict[str, Any]: ...
def clear_shard_cache() -> None: ...

# ============== Background Timeout ==============

def set_background_timeout(timeout: float) -> None: ...
def get_background_timeout() -> float: ...

# ============== Preferences ==============

def save_preferences() -> bool: ...
def load_preferences() -> Dict[str, str]: ...
def apply_preferences() -> None: ...
def clear_preferences() -> bool: ...

# ============== Dependency Tree ==============

def dependency_tree(module_name: str, max_depth: int = 3, include_stdlib: bool = True, include_third_party: bool = True, include_local: bool = True) -> DependencyTree: ...
def print_dependency_tree(tree: DependencyTree) -> None: ...

# ============== Module-level attributes ==============

__all__: List[str]

def __getattr__(name: str) -> Union[LazyModule, LazySymbol, Any]: ...
def __dir__() -> List[str]: ...