# Backward-compatible redirect to laziest_import._symbol
from . import (
    clear_symbol_preference,
    disable_auto_symbol_resolution,
    disable_symbol_search,
    enable_auto_symbol_resolution,
    enable_symbol_search,
    get_loaded_modules_context,
    get_module_priority,
    get_module_skip_config,
    get_symbol_cache_info,
    get_symbol_preference,
    get_symbol_resolution_config,
    get_symbol_search_config,
    is_symbol_search_enabled,
    list_symbol_conflicts,
    rebuild_symbol_index,
    set_module_priority,
    set_module_skip_config,
    set_symbol_preference,
)

__all__ = [
    "clear_symbol_preference",
    "disable_auto_symbol_resolution",
    "disable_symbol_search",
    "enable_auto_symbol_resolution",
    "enable_symbol_search",
    "get_loaded_modules_context",
    "get_module_priority",
    "get_module_skip_config",
    "get_symbol_cache_info",
    "get_symbol_preference",
    "get_symbol_resolution_config",
    "get_symbol_search_config",
    "is_symbol_search_enabled",
    "list_symbol_conflicts",
    "rebuild_symbol_index",
    "set_module_priority",
    "set_module_skip_config",
    "set_symbol_preference",
]
