# Backward-compatible redirect to laziest_import._symbol
from . import (
    enable_symbol_search as enable_symbol_search,
    disable_symbol_search as disable_symbol_search,
    is_symbol_search_enabled as is_symbol_search_enabled,
    rebuild_symbol_index as rebuild_symbol_index,
    get_symbol_search_config as get_symbol_search_config,
    get_symbol_cache_info as get_symbol_cache_info,
    set_symbol_preference as set_symbol_preference,
    get_symbol_preference as get_symbol_preference,
    clear_symbol_preference as clear_symbol_preference,
    list_symbol_conflicts as list_symbol_conflicts,
    set_module_priority as set_module_priority,
    get_module_priority as get_module_priority,
    enable_auto_symbol_resolution as enable_auto_symbol_resolution,
    disable_auto_symbol_resolution as disable_auto_symbol_resolution,
    get_symbol_resolution_config as get_symbol_resolution_config,
    get_loaded_modules_context as get_loaded_modules_context,
    get_module_skip_config as get_module_skip_config,
    set_module_skip_config as set_module_skip_config,
)

__all__ = [
    "enable_symbol_search",
    "disable_symbol_search",
    "is_symbol_search_enabled",
    "rebuild_symbol_index",
    "get_symbol_search_config",
    "get_symbol_cache_info",
    "set_symbol_preference",
    "get_symbol_preference",
    "clear_symbol_preference",
    "list_symbol_conflicts",
    "set_module_priority",
    "get_module_priority",
    "enable_auto_symbol_resolution",
    "disable_auto_symbol_resolution",
    "get_symbol_resolution_config",
    "get_loaded_modules_context",
    "get_module_skip_config",
    "set_module_skip_config",
]